blank_issues_enabled: false
contact_links:
  - name: Team Empire
    url: https://t.me/TheEmpireGroup
    about: Updates Channels
  - name: GroupEmpireOT
    url: https://t.me/GroupEmpireOT
    about: Support Group
